openapi: 3.0.0
info:
  title: Stripe Go Spike API
  description: Minimal endpoints for a Stripe integration spike.
  version: 0.1.0
servers:
  - url: http://localhost:8060/api
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
  /checkout-session:
    post:
      summary: Create a mock checkout session (replace with stripe-go during spike)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                priceId:
                  type: string
                amount:
                  type: integer
                currency:
                  type: string
      responses:
        '200':
          description: Created mock session
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  createdAt:
                    type: string
                    format: date-time
        '400':
          description: Bad request
  /webhook:
    post:
      summary: Receive Stripe webhook events (mock)
      responses:
        '204':
          description: No Content
