// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.deleteCacheKeyStmt, err = db.PrepareContext(ctx, deleteCacheKey); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCacheKey: %w", err)
	}
	if q.getCacheValueStmt, err = db.PrepareContext(ctx, getCacheValue); err != nil {
		return nil, fmt.Errorf("error preparing query GetCacheValue: %w", err)
	}
	if q.listCacheStmt, err = db.PrepareContext(ctx, listCache); err != nil {
		return nil, fmt.Errorf("error preparing query ListCache: %w", err)
	}
	if q.setCacheValueStmt, err = db.PrepareContext(ctx, setCacheValue); err != nil {
		return nil, fmt.Errorf("error preparing query SetCacheValue: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.deleteCacheKeyStmt != nil {
		if cerr := q.deleteCacheKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCacheKeyStmt: %w", cerr)
		}
	}
	if q.getCacheValueStmt != nil {
		if cerr := q.getCacheValueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCacheValueStmt: %w", cerr)
		}
	}
	if q.listCacheStmt != nil {
		if cerr := q.listCacheStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCacheStmt: %w", cerr)
		}
	}
	if q.setCacheValueStmt != nil {
		if cerr := q.setCacheValueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setCacheValueStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                 DBTX
	tx                 *sql.Tx
	deleteCacheKeyStmt *sql.Stmt
	getCacheValueStmt  *sql.Stmt
	listCacheStmt      *sql.Stmt
	setCacheValueStmt  *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                 tx,
		tx:                 tx,
		deleteCacheKeyStmt: q.deleteCacheKeyStmt,
		getCacheValueStmt:  q.getCacheValueStmt,
		listCacheStmt:      q.listCacheStmt,
		setCacheValueStmt:  q.setCacheValueStmt,
	}
}
