// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type AuditEvent struct {
	ID          int64          `json:"id"`
	Timestamp   string         `json:"timestamp"`
	Subsystem   string         `json:"subsystem"`
	EventType   string         `json:"event_type"`
	UserID      sql.NullString `json:"user_id"`
	Information sql.NullString `json:"information"`
	Payload     sql.NullString `json:"payload"`
	RefID       sql.NullString `json:"ref_id"`
	RefId2      sql.NullString `json:"ref_id2"`
}

type Cache struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Transaction struct {
	ID                    string         `json:"id"`
	UserID                string         `json:"user_id"`
	ProductID             string         `json:"product_id"`
	ProductName           string         `json:"product_name"`
	Amount                int64          `json:"amount"`
	StripeSessionID       sql.NullString `json:"stripe_session_id"`
	StripePaymentIntentID sql.NullString `json:"stripe_payment_intent_id"`
	Status                string         `json:"status"`
	CreatedAt             string         `json:"created_at"`
	UpdatedAt             string         `json:"updated_at"`
}
