// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	DeleteCacheKey(ctx context.Context, key string) error
	GetCacheValue(ctx context.Context, key string) (string, error)
	ListCache(ctx context.Context) ([]Cache, error)
	SetCacheValue(ctx context.Context, arg SetCacheValueParams) error
}

var _ Querier = (*Queries)(nil)
