// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) error
	DeleteCacheKey(ctx context.Context, key string) error
	GetAllAuditEvents(ctx context.Context, arg GetAllAuditEventsParams) ([]AuditEvent, error)
	GetAuditEventsByEventType(ctx context.Context, arg GetAuditEventsByEventTypeParams) ([]AuditEvent, error)
	GetAuditEventsByRefID(ctx context.Context, arg GetAuditEventsByRefIDParams) ([]AuditEvent, error)
	GetAuditEventsByRefID2(ctx context.Context, arg GetAuditEventsByRefID2Params) ([]AuditEvent, error)
	GetAuditEventsBySubsystem(ctx context.Context, arg GetAuditEventsBySubsystemParams) ([]AuditEvent, error)
	GetAuditEventsBySubsystemAndType(ctx context.Context, arg GetAuditEventsBySubsystemAndTypeParams) ([]AuditEvent, error)
	GetAuditEventsByUser(ctx context.Context, arg GetAuditEventsByUserParams) ([]AuditEvent, error)
	GetAuditEventsInDateRange(ctx context.Context, arg GetAuditEventsInDateRangeParams) ([]AuditEvent, error)
	GetCacheValue(ctx context.Context, key string) (string, error)
	GetTransaction(ctx context.Context, id string) (Transaction, error)
	GetTransactionByStripeSessionID(ctx context.Context, stripeSessionID sql.NullString) (Transaction, error)
	ListAllTransactions(ctx context.Context, arg ListAllTransactionsParams) ([]Transaction, error)
	ListCache(ctx context.Context) ([]Cache, error)
	ListTransactionsByUserID(ctx context.Context, arg ListTransactionsByUserIDParams) ([]Transaction, error)
	SetCacheValue(ctx context.Context, arg SetCacheValueParams) error
	UpdateTransactionByPaymentIntentID(ctx context.Context, arg UpdateTransactionByPaymentIntentIDParams) error
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) error
	UpdateTransactionWithStripeData(ctx context.Context, arg UpdateTransactionWithStripeDataParams) error
}

var _ Querier = (*Queries)(nil)
